# Defaults
 kramdown:
  input: GFM
  hard_wrap: false

# Permalinks
permalink:        pretty

# Setup
title:            TiTlE
tagline:          'JS nuggets from an early web dev career'
description:      "There is a lot I don't know, some of it might be of interest to you."
url:              http://til.florianpellet.com
baseurl:          /
test:             TheBigQuizz

author:
  name:           'Florian Pellet'
  url:            https://florianpellet.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sheraff/til
