# Defaults

kramdown:
  input: GFM
  hard_wrap: false

# Permalinks
permalink:        pretty

# Setup
title:            Today I Learned
tagline:          'JS nuggets from an early web dev career'
description:      >
  I like JS, reading the mozilla doc, diving into github, cramming on google dev blogs... 
  Here's some of what I learned from it.
url:              http://til.florianpellet.com
baseurl:          /
baseurl2:         ./
baseurl3:         '.'
test:             TheBigQuizz

author:
  name:           'Florian Pellet'
  url:            https://florianpellet.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sheraff/til
